{
 "title": "Calico dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(calico_bgp_peer_info, cluster)"
    }
   },
   {
    "name": "mode",
    "label": "mode",
    "query": {
     "query": "label_values(calico_bgp_peer_info, mode)"
    }
   },
   {
    "name": "instance",
    "label": "node",
    "query": {
     "query": "label_values(calico_bgp_peer_info{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "bgp_peer_name",
    "label": "peer",
    "query": {
     "query": "label_values(calico_bgp_peer_info{cluster=\"$cluster\", instance=\"$instance\", mode=\"$mode\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "general info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(calico_bgp_bird_info{cluster=\"$cluster\"})",
     "legendFormat": "BGP bird"
    },
    {
     "expr": "count(calico_bgp_peer_info{cluster=\"$cluster\", mode=\"$mode\"})",
     "legendFormat": "BGP peer"
    },
    {
     "expr": "sum(calico_ippools{cluster=\"$cluster\"})",
     "legendFormat": "IPPool"
    },
    {
     "expr": "sum(calico_ipam_blocks{cluster=\"$cluster\"})",
     "legendFormat": "IP block"
    }
   ]
  },
  {
   "title": "BGP error info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(calico_bgp_bird_info{cluster=\"$cluster\", up!=\"true\"}) or vector(0)",
     "legendFormat": "Inactive BGP bird"
    },
    {
     "expr": "count(calico_bgp_peer_info{cluster=\"$cluster\", bgp_state!=\"up\", mode=\"$mode\"} or calico_bgp_peer_info{cluster=\"$cluster\", conn_state!=\"Established\", mode=\"$mode\"}) or vector(0)",
     "legendFormat": "Inactive BGP peer"
    }
   ]
  },
  {
   "title": "ip allocations per ippool",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "calico_ippool_allocated_ips{cluster=\"$cluster\"} * 100 / calico_ippool_capacity{cluster=\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "BGP Peers per node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(calico_bgp_peer_info{cluster=\"$cluster\", mode=\"$mode\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ip allocations per node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(calico_ipam_allocations_per_node) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ipblocks per node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "calico_ipam_blocks_per_node{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "BGP Peer route status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "calico_bgp_route_import_updates_received_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import updates received"
    },
    {
     "expr": "calico_bgp_route_import_updates_rejected_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import updates rejected"
    },
    {
     "expr": "calico_bgp_route_import_updates_filtered_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import updates filtered"
    },
    {
     "expr": "calico_bgp_route_import_updates_ignored_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import updates ignored"
    },
    {
     "expr": "calico_bgp_route_import_updates_filtered_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import updates accepted"
    },
    {
     "expr": "calico_bgp_route_import_withdraws_received_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import withdraws received"
    },
    {
     "expr": "calico_bgp_route_import_withdraws_rejected_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import withdraws rejected"
    },
    {
     "expr": "calico_bgp_route_import_withdraws_ignored_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import withdraws ignored"
    },
    {
     "expr": "calico_bgp_route_import_withdraws_accepted_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "import withdraws accepted"
    },
    {
     "expr": "calico_bgp_route_export_updates_received_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export updates received"
    },
    {
     "expr": "calico_bgp_route_export_updates_rejected_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export updates rejected"
    },
    {
     "expr": "calico_bgp_route_export_updates_filtered_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export updates filtered"
    },
    {
     "expr": "calico_bgp_route_export_updates_accepted_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export updates accepted"
    },
    {
     "expr": "calico_bgp_route_export_withdraws_received_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export withdraws received"
    },
    {
     "expr": "calico_bgp_route_export_withdraws_accepted_total{cluster=\"$cluster\", instance=\"$instance\", name=\"$bgp_peer_name\"}",
     "legendFormat": "export withdraws accepted"
    }
   ]
  },
  {
   "title": "ip allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "calico_ipam_allocations_per_node{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ip allocations borrowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "calico_ipam_allocations_borrowed{cluster=\"$cluster\"}",
     "legendFormat": "{{ippool}}-{{node}}"
    }
   ]
  },
  {
   "title": "ip allocations gc candidates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "calico_ipam_allocations_gc_candidates{cluster=\"$cluster\"}",
     "legendFormat": "{{ippool}}-{{node}}"
    }
   ]
  },
  {
   "title": "IPPool info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "calico_ippool_info{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "BGP Peer info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "calico_bgp_peer_info{cluster=\"$cluster\", mode=\"$mode\"}",
     "legendFormat": "{{instance}} - {{ip}}"
    }
   ]
  }
 ]
}